package seeders

import (
	"dnd-api/db/models"
	"log"
)

func (s *Seeder) SetCharactersInventory() {
	characterInventoryItems := []models.CharacterInventoryItem{
		{
			ID:          1,
			CharacterID: 1,
			ItemID:      17,
			Equipped:    true,
			Location:    "Equipment",
		},
		{
			ID:          2,
			CharacterID: 1,
			ItemID:      7,
			Quantity:    1,
			Location:    "Equipment",
		},
		{
			ID:          3,
			CharacterID: 1,
			ItemID:      8,
			Equipped:    true,
			Quantity:    20,
			Location:    "Equipment",
		},
		{
			ID:          4,
			CharacterID: 1,
			ItemID:      3,
			Equipped:    true,
			Location:    "Equipment",
		},
		{
			ID:          5,
			CharacterID: 1,
			ItemID:      1,
			Equipped:    true,
			Location:    "Equipment",
		},
		{
			ID:          6,
			CharacterID: 1,
			ItemID:      1,
			Equipped:    false,
			Location:    "Equipment",
		},
		{
			ID:          7,
			CharacterID: 1,
			ItemID:      5,
			Quantity:    1,
			Location:    "Equipment",
		},
		{
			ID:          8,
			CharacterID: 1,
			ItemID:      9,
			Quantity:    1,
			Location:    "Equipment",
		},
		{
			ID:          9,
			CharacterID: 1,
			ItemID:      4,
			Equipped:    true,
			Location:    "Equipment",
		},
		{
			ID:          10,
			CharacterID: 1,
			ItemID:      10,
			Quantity:    1,
			Location:    "Backpack",
		},
		{
			ID:          11,
			CharacterID: 1,
			ItemID:      11,
			Quantity:    1,
			Location:    "Backpack",
		},
		{
			ID:          12,
			CharacterID: 1,
			ItemID:      12,
			Quantity:    10,
			Location:    "Backpack",
		},
		{
			ID:          13,
			CharacterID: 1,
			ItemID:      13,
			Quantity:    1,
			Location:    "Backpack",
		},
		{
			ID:          14,
			CharacterID: 1,
			ItemID:      14,
			Quantity:    1,
			Location:    "Backpack",
		},
		{
			ID:          15,
			CharacterID: 1,
			ItemID:      15,
			Quantity:    10,
			Location:    "Backpack",
		},
		{
			ID:          16,
			CharacterID: 1,
			ItemID:      16,
			Quantity:    1,
			Location:    "Backpack",
		},
		{
			ID:          17,
			CharacterID: 2,
			ItemID:      18,
			Equipped:    true,
			Location:    "Equipment",
		},
		{
			ID:          18,
			CharacterID: 2,
			ItemID:      18,
			Equipped:    true,
			Location:    "Equipment",
		},
		{
			ID:          19,
			CharacterID: 2,
			ItemID:      18,
			Equipped:    false,
			Location:    "Equipment",
		},
		{
			ID:          20,
			CharacterID: 2,
			ItemID:      18,
			Equipped:    false,
			Location:    "Equipment",
		},
		{
			ID:          21,
			CharacterID: 2,
			ItemID:      19,
			Equipped:    true,
			Location:    "Equipment",
		},
		{
			ID:          22,
			CharacterID: 2,
			ItemID:      20,
			Quantity:    1,
			Location:    "Equipment",
		},
		{
			ID:          23,
			CharacterID: 2,
			ItemID:      21,
			Quantity:    1,
			Location:    "Equipment",
		},
		{
			ID:          24,
			CharacterID: 2,
			ItemID:      22,
			Equipped:    true,
			Location:    "Equipment",
		},
		{
			ID:          25,
			CharacterID: 2,
			ItemID:      10,
			Quantity:    1,
			Location:    "Backpack",
		},
		{
			ID:          26,
			CharacterID: 2,
			ItemID:      11,
			Quantity:    1,
			Location:    "Backpack",
		},
		{
			ID:          27,
			CharacterID: 2,
			ItemID:      5,
			Quantity:    1,
			Location:    "Backpack",
		},
		{
			ID:          28,
			CharacterID: 2,
			ItemID:      12,
			Quantity:    10,
			Location:    "Backpack",
		},
		{
			ID:          29,
			CharacterID: 2,
			ItemID:      13,
			Quantity:    1,
			Location:    "Backpack",
		},
		{
			ID:          30,
			CharacterID: 2,
			ItemID:      23,
			Quantity:    1,
			Location:    "Backpack",
		},
		{
			ID:          31,
			CharacterID: 2,
			ItemID:      14,
			Quantity:    1,
			Location:    "Backpack",
		},
		{
			ID:          32,
			CharacterID: 2,
			ItemID:      15,
			Quantity:    9,
			Location:    "Backpack",
		},
		{
			ID:          33,
			CharacterID: 3,
			ItemID:      7,
			Quantity:    1,
			Location:    "Equipment",
		},
		{
			ID:          34,
			CharacterID: 3,
			ItemID:      20,
			Quantity:    1,
			Location:    "Equipment",
		},
		{
			ID:          35,
			CharacterID: 3,
			ItemID:      1,
			Equipped:    true,
			Location:    "Equipment",
		},
		{
			ID:          36,
			CharacterID: 3,
			ItemID:      24,
			Equipped:    true,
			Location:    "Equipment",
		},
		{
			ID:          37,
			CharacterID: 3,
			ItemID:      25,
			Equipped:    true,
			Location:    "Equipment",
		},
		{
			ID:          38,
			CharacterID: 3,
			ItemID:      26,
			Quantity:    1,
			Location:    "Equipment",
		},
		{
			ID:          39,
			CharacterID: 3,
			ItemID:      27,
			Equipped:    false,
			Location:    "Equipment",
		},
		{
			ID:          40,
			CharacterID: 3,
			ItemID:      10,
			Quantity:    1,
			Location:    "Backpack",
		},
		{
			ID:          41,
			CharacterID: 3,
			ItemID:      11,
			Quantity:    1,
			Location:    "Backpack",
		},
		{
			ID:          42,
			CharacterID: 3,
			ItemID:      12,
			Quantity:    10,
			Location:    "Backpack",
		},
		{
			ID:          43,
			CharacterID: 3,
			ItemID:      28,
			Quantity:    1,
			Location:    "Backpack",
		},
		{
			ID:          44,
			CharacterID: 3,
			ItemID:      14,
			Quantity:    1,
			Location:    "Backpack",
		},
		{
			ID:          45,
			CharacterID: 3,
			ItemID:      15,
			Quantity:    9,
			Location:    "Backpack",
		},
		{
			ID:          46,
			CharacterID: 3,
			ItemID:      16,
			Quantity:    1,
			Location:    "Backpack",
		},
		{
			ID:          47,
			CharacterID: 4,
			ItemID:      29,
			Equipped:    true,
			Location:    "Equipment",
		},
		{
			ID:          48,
			CharacterID: 4,
			ItemID:      30,
			Equipped:    true,
			Location:    "Equipment",
		},
		{
			ID:          49,
			CharacterID: 4,
			ItemID:      20,
			Quantity:    1,
			Location:    "Equipment",
		},
		{
			ID:          50,
			CharacterID: 4,
			ItemID:      2,
			Equipped:    true,
			Location:    "Equipment",
		},
		{
			ID:          51,
			CharacterID: 4,
			ItemID:      36,
			Equipped:    true,
			Location:    "Equipment",
		},
		{
			ID:          52,
			CharacterID: 4,
			ItemID:      36,
			Equipped:    false,
			Location:    "Equipment",
		},
		{
			ID:          53,
			CharacterID: 4,
			ItemID:      31,
			Equipped:    true,
			Location:    "Equipment",
		},
		{
			ID:          54,
			CharacterID: 4,
			ItemID:      31,
			Equipped:    false,
			Location:    "Equipment",
		},
		{
			ID:          55,
			CharacterID: 4,
			ItemID:      5,
			Quantity:    1,
			Location:    "Equipment",
		},
		{
			ID:          56,
			CharacterID: 4,
			ItemID:      32,
			Quantity:    1,
			Location:    "Backpack",
		},
		{
			ID:          57,
			CharacterID: 4,
			ItemID:      33,
			Quantity:    1,
			Location:    "Backpack",
		},
		{
			ID:          58,
			CharacterID: 4,
			ItemID:      34,
			Quantity:    1,
			Location:    "Backpack",
		},
		{
			ID:          59,
			CharacterID: 4,
			ItemID:      35,
			Quantity:    10,
			Location:    "Backpack",
		},
		{
			ID:          60,
			CharacterID: 4,
			ItemID:      12,
			Quantity:    9,
			Location:    "Backpack",
		},
		{
			ID:          61,
			CharacterID: 4,
			ItemID:      13,
			Quantity:    1,
			Location:    "Backpack",
		},
		{
			ID:          62,
			CharacterID: 4,
			ItemID:      14,
			Quantity:    1,
			Location:    "Backpack",
		},
		{
			ID:          63,
			CharacterID: 4,
			ItemID:      15,
			Quantity:    10,
			Location:    "Backpack",
		},
		{
			ID:          64,
			CharacterID: 4,
			ItemID:      16,
			Quantity:    1,
			Location:    "Backpack",
		},
	}

	for _, item := range characterInventoryItems {
		err := s.DB.Where("id = ?", item.ID).FirstOrCreate(&item).Error
		if err != nil {
			log.Printf("error creating character inventory item with id: %v -- %s", item.ID, err.Error())
		}
	}
}
