package seeders

import (
	"dungeons-and-dragons/db/models"
	"log"
)

func (s *Seeder) SetRaces() {
	races := []models.Race{
		{ID: 1, Name: "Aarakocra", Description: "Sequestered in high mountains atop tall trees, the aarakocra, sometimes called birdfolk, evoke fear and wonder."},
		{ID: 2, Name: "Dragonborn", Description: "Dragonborn look very much like dragons standing erect in humanoid form, though they lack wings or a tail."},
		{ID: 3, Name: "Hill Dwarf", Description: "Bold and hardy, dwarves are known as skilled warriors, miners, and workers of stone and metal.\nAs a hill dwarf, you have keen senses, deep intuition, and remarkable resilience. The gold dwarves of Faerûn in their mighty southern kingdom are hill dwarves, as are the exiled Neidar and the debased Klar of Krynn in the Dragonlance setting."},
		{ID: 4, Name: "Moutain Dwarf", Description: "Bold and hardy, dwarves are known as skilled warriors, miners, and workers of stone and metal.\nAs a mountain dwarf, you’re strong and hardy, accustomed to a difficult life in rugged terrain. You’re probably on the tall side (for a dwarf), and tend toward lighter coloration. The shield dwarves of northern Faerûn, as well as the ruling Hylar clan and the noble Daewar clan of Dragonlance, are mountain dwarves."},
		{ID: 5, Name: "Eladrin Elf", Description: "Elves are a magical people of otherworldly grace, living in the world but not entirely part of it.\nThis version of the eladrin originally appeared in the Dungeon Master's Guide as an example for creating your own subraces.\nCreatures of magic with strong ties to nature, eladrin live in the twilight realm of the Feywild. Their cities sometimes cross over to the Material Plane, appearing briefly in mountain valleys or deep forest glades before fading back into the Feywild."},
		{ID: 6, Name: "High Elf", Description: "Elves are a magical people of otherworldly grace, living in the world but not entirely part of it.\nAs a high elf, you have a keen mind and a mastery of at least the basics of magic. In many of the worlds of D&D, there are two kinds of high elves. One type (which includes the gray elves and valley elves of Greyhawk, the Silvanesti of Dragonlance, and the sun elves of the Forgotten Realms) is haughty and reclusive, believing themselves to be superior to non-elves and even other elves. The other type (including the high elves of Greyhawk, the Qualinesti of Dragonlance, and the moon elves of the Forgotten Realms) are more common and more friendly, and often encountered among humans and other races.\nThe sun elves of Faerûn (also called gold elves or sunrise elves) have bronze skin and hair of copper, black, or golden blond. Their eyes are golden, silver, or black. Moon elves (also called silver elves or gray elves) are much paler, with alabaster skin sometimes tinged with blue. They often have hair of silver-white, black, or blue, but various shades of blond, brown, and red are not uncommon. Their eyes are blue or green and flecked with gold."},
		{ID: 7, Name: "Wood Elf", Description: "Elves are a magical people of otherworldly grace, living in the world but not entirely part of it.\nAs a wood elf, you have keen senses and intuition, and your fleet feet carry you quickly and stealthily through your native forests. This category includes the wild elves (grugach) of Greyhawk and the Kagonesti of Dragonlance, as well as the races called wood elves in Greyhawk and the Forgotten Realms. In Faerûn, wood elves (also called wild elves, green elves, or forest elves) are reclusive and distrusting of non-elves.\nWood elves’ skin tends to be copperish in hue, sometimes with traces of green. Their hair tends toward browns and blacks, but it is occasionally blond or copper-colored. Their eyes are green, brown, or hazel."},
		{ID: 8, Name: "Air Genasi", Description: "Genasi carry the power of the elemental planes of air, earth, fire, and water in their blood.\nAs an air genasi, you are descended from the djinn. As changeable as the weather, your moods shift from calm to wild and violent with little warning, but these storms rarely last long.\nAir genasi typically have light blue skin, hair, and eyes. A faint but constant breeze accompanies them, tousling the hair and stirring the clothing. Some air genasi speak with breathy voices, marked by a faint echo. A few display odd patterns in their flesh or grow crystals from their scalps."},
		{ID: 9, Name: "Earth Genasi", Description: "Genasi carry the power of the elemental planes of air, earth, fire, and water in their blood.\nAs an earth genasi, you are descended from the cruel and greedy dao, though you aren’t necessarily evil. You have inherited some measure of control over earth, reveling in superior strength and solid power. You tend to avoid rash decisions, pausing long enough to consider your options before taking action.\nElemental earth manifests differently from one individual to the next. Some earth genasi always have bits of dust falling from their bodies and mud clinging to their clothes, never getting clean no matter how often they bathe. Others are as shiny and polished as gemstones, with skin tones of deep brown or black, eyes sparkling like agates. Earth genasi can also have smooth metallic flesh, dull iron skin spotted with rust, a pebbled and rough hide, or even a coating of tiny embedded crystals. The most arresting have fissures in their flesh, from which faint light shines."},
		{ID: 10, Name: "Fire Genasi", Description: "Genasi carry the power of the elemental planes of air, earth, fire, and water in their blood.\nAs a fire genasi, you have inherited the volatile mood and keen mind of the efreet. You tend toward impatience and making snap judgments. Rather than hide your distinctive appearance, you exult in it.\nNearly all fire genasi are feverishly hot as if burning inside, an impression reinforced by flaming red, coal- black, or ash-gray skin tones. The more human-looking have fiery red hair that writhes under extreme emotion, while more exotic specimens sport actual flames dancing on their heads. Fire genasi voices might sound like crackling flames, and their eyes flare when angered. Some are accompanied by the faint scent of brimstone."},
		{ID: 11, Name: "Water Genasi", Description: "Genasi carry the power of the elemental planes of air, earth, fire, and water in their blood.\nThe lapping of waves, the spray of sea foam on the wind, the ocean depths—all of these things call to your heart. You wander freely and take pride in your independence, though others might consider you selfish.\nMost water genasi look as if they just finished bathing, with beads of moisture collecting on their skin and hair. They smell of fresh rain and clean water. Blue or green skin is common, and most have somewhat overlarge eyes, blue-black in color. A water genasi’s hair might float freely, swaying and waving as if underwater. Some have voices with undertones reminiscent of whale song or trickling streams."},
		{ID: 12, Name: "Rock Gnome", Description: "A gnome’s energy and enthusiasm for living shines through every inch of his or her tiny body.\nAs a rock gnome, you have a natural inventiveness and hardiness beyond that of other gnomes. Most gnomes in the worlds of D&D are rock gnomes, including the tinker gnomes of the Dragonlance setting."},
		{ID: 13, Name: "Deep Gnome", Description: "A gnome’s energy and enthusiasm for living shines through every inch of his or her tiny body.\nForest gnomes and rock gnomes are the gnomes most commonly encountered in the lands of the surface world. There is another subrace of gnomes rarely seen by any surface-dweller: deep gnomes, also known as svirfneblin. Guarded, and suspicious of outsiders, svirfneblin are cunning and taciturn, but can be just as kind-hearted, loyal, and compassionate as their surface cousins."},
		{ID: 14, Name: "Goliath", Description: "Strong and reclusive, every day brings a new challenge to a goliath."},
		{ID: 15, Name: "Half-Elf", Description: "Half-elves combine what some say are the best qualities of their elf and human parents."},
		{ID: 16, Name: "Half-Orc", Description: "Some half-orcs rise to become proud leaders of orc communities. Some venture into the world to prove their worth. Many of these become adventurers, achieving greatness for their mighty deeds."},
		{ID: 17, Name: "Lightfoot Halfling", Description: "The diminutive halflings survive in a world full of larger creatures by avoiding notice or, barring that, avoiding offense.\nAs a lightfoot halfling, you can easily hide from notice, even using other people as cover. You’re inclined to be affable and get along well with others. In the Forgotten Realms, lightfoot halflings have spread the farthest and thus are the most common variety.\nLightfoots are more prone to wanderlust than other halflings, and often dwell alongside other races or take up a nomadic life. In the world of Greyhawk, these halflings are called hairfeet or tallfellows."},
		{ID: 18, Name: "Stout Halfling", Description: "The diminutive halflings survive in a world full of larger creatures by avoiding notice or, barring that, avoiding offense.\nAs a stout halfling, you’re hardier than average and have some resistance to poison. Some say that stouts have dwarven blood. In the Forgotten Realms, these halflings are called stronghearts, and they’re most common in the south."},
		{ID: 19, Name: "Human", Description: "Humans are the most adaptable and ambitious people among the common races. Whatever drives them, humans are the innovators, the achievers, and the pioneers of the worlds."},
		{ID: 20, Name: "Variant Human", Description: "Humans are the most adaptable and ambitious people among the common races. Whatever drives them, humans are the innovators, the achievers, and the pioneers of the worlds.\nIf your campaign uses the optional feat rules from the Player’s Handbook, your Dungeon Master might allow these variant traits, all of which replace the human’s Ability Score Increase trait."},
		{ID: 21, Name: "Tiefling", Description: "To be greeted with stares and whispers, to suffer violence and insult on the street, to see mistrust and fear in every eye: this is the lot of the tiefling."},
		{ID: 22, Name: "Variant Aasimar", Description: "Aasimar are placed in the world to serve as guardians of law and good. Their patrons expect them to strike at evil, lead by example, and further the cause of justice.\nThis aasimar variant originally appeared in the Dungeon Master's Guide as an example for creating your own races.\nWhereas tieflings have fiendish blood in their veins, aasimar are the descendants of celestial beings. These folk generally appear as glorious humans with lustrous hair, flawless skin, and piercing eyes. Aasimar often attempt to pass as humans in order to right wrongs and defend goodness on the Material Plane without drawing undue attention to their celestial heritage. They strive to fit into society, although they usually rise to the top, becoming revered leaders and honorable heroes."},
	}

	for _, race := range races {
		err := s.DB.Where("id = ?", race.ID).FirstOrCreate(&race).Error
		if err != nil {
			log.Printf("error creating race %s: %v", race.Name, err.Error())
		}
	}
}
